name: PHPUnit

on:
  push:
    branches:
      - dev

jobs:
  phpunit:
    name: PHPUnit

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: 
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_USER: VINCULACON
          MYSQL_PASSWORD: user
          MYSQL_DATABASE: dbname

    steps:
    - uses: actions/checkout@v1
    - uses: michelmelo/slim-phpunit-action@master
